name: Periodic health check

on:
  workflow_dispatch:
  schedule: 
    - cron: '*/15 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fs-pokedex-airy-wind-1568.fly.dev/health
          max-attempts: 3
          retry-delay: 5s